// _SUUpdateAlert_EOArchive_Polish.java
// Generated by EnterpriseObjects palette at sobota, 25 marca 2006 14:46:01 Europe/Warsaw

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _SUUpdateAlert_EOArchive_Polish extends com.webobjects.eoapplication.EOArchive {
    UserDefaultsController _userDefaultsController0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _webClipView0, _webDynamicScrollBarsView0, _webFrameView0, _webView0;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2;
    javax.swing.JCheckBox _nsButton3;
    javax.swing.JPanel _nsView0;

    public _SUUpdateAlert_EOArchive_Polish(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _userDefaultsController0 = (UserDefaultsController)_registered(new UserDefaultsController(), "Shared Defaults");
        _nsButton3 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Automatically download and install updates in the future"), "NSButton4");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Instaluj uaktualnienie"), "NSButton");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Przypomnij p\u00f3\u017aniej"), "NSButton1");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Pomi\u0144 t\u0119 wersj\u0119"), "NSButton2");
        _webClipView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _webDynamicScrollBarsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _webFrameView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "releaseNotesView")) != null)) {
            _webView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_webView0");
        } else {
            _webView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "WebView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "description")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Update Alert (release notes)");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "installUpdate", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_eoFrame0, _owner(), "delegate");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "remindMeLater", _nsButton1), ""));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "skipThisVersion", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_webView0") == null) {
            _connect(_owner(), _webView0, "releaseNotesView");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "description");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsButton3, "Lucida Grande", 11, Font.PLAIN);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _webView0.setSize(494, 244);
        _webView0.setLocation(0, 0);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_webView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox1.add(_webView0);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(494, 244);
        _nsBox1.setLocation(1, 1);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN + Font.BOLD);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Uwagi o wydaniu:");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        if (!(_webDynamicScrollBarsView0.getLayout() instanceof EOViewLayout)) { _webDynamicScrollBarsView0.setLayout(new EOViewLayout()); }
        _webClipView0.setSize(494, 244);
        _webClipView0.setLocation(0, 0);
        ((EOViewLayout)_webDynamicScrollBarsView0.getLayout()).setAutosizingMask(_webClipView0, EOViewLayout.MinYMargin);
        _webDynamicScrollBarsView0.add(_webClipView0);
        if (!(_webFrameView0.getLayout() instanceof EOViewLayout)) { _webFrameView0.setLayout(new EOViewLayout()); }
        _webDynamicScrollBarsView0.setSize(494, 244);
        _webDynamicScrollBarsView0.setLocation(0, 0);
        ((EOViewLayout)_webFrameView0.getLayout()).setAutosizingMask(_webDynamicScrollBarsView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _webFrameView0.add(_webDynamicScrollBarsView0);

        if (_replacedObjects.objectForKey("_webView0") == null) {
            if (!(_webView0.getLayout() instanceof EOViewLayout)) { _webView0.setLayout(new EOViewLayout()); }
            _webFrameView0.setSize(494, 244);
            _webFrameView0.setLocation(0, 0);
            ((EOViewLayout)_webView0.getLayout()).setAutosizingMask(_webFrameView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
            _webView0.add(_webFrameView0);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField1.setEditable(false);
            _nsTextField1.setOpaque(false);
            _nsTextField1.setText("Description (set in code)");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(false);
            _nsTextField1.setEnabled(true);
            _nsTextField1.setBorder(null);
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN + Font.BOLD);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("A new version of APP_NAME is available! (set in code)");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsImageView0.setSize(64, 64);
        _nsImageView0.setLocation(17, 9);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsImageView0);
        _nsTextField0.setSize(455, 17);
        _nsTextField0.setLocation(100, 9);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField1.setSize(502, 14);
        _nsTextField1.setLocation(100, 34);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField2.setSize(104, 14);
        _nsTextField2.setLocation(100, 56);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField2);
        _nsButton1.setSize(155, 26);
        _nsButton1.setLocation(272, 358);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsButton0.setSize(133, 26);
        _nsButton0.setLocation(101, 358);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsBox0.setSize(496, 246);
        _nsBox0.setLocation(102, 80);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsBox0);
        _nsButton3.setSize(326, 15);
        _nsButton3.setLocation(99, 336);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton3);
        _nsButton2.setSize(169, 26);
        _nsButton2.setLocation(433, 358);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton2);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(611, 394);
            _eoFrame0.setTitle("Software Update");
            _eoFrame0.setLocation(204, 84);
            _eoFrame0.setSize(611, 394);
        }
    }
}
